# Generated by Django 3.1.4 on 2021-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Name')),
                ('client_email', models.EmailField(max_length=300, verbose_name='Email')),
                ('client_message', models.TextField(verbose_name='Messages')),
                ('message_draft_on', models.DateTimeField(null=True, verbose_name='Drafted On')),
            ],
        ),
    ]
